"""Added image_url

Revision ID: 32b53647d0d2
Revises: 50d10213c0c8
Create Date: 2025-03-26 17:02:53.206643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b53647d0d2'
down_revision: Union[str, None] = '50d10213c0c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptocurrencies', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cryptocurrencies', 'image_url')
    # ### end Alembic commands ###
